config/routes.rb
TxivrWaterDemo::Application.routes.draw do
  resources :readings
  match 'create_meter_reading' => 'Readings#create_meter_reading'

  resources :users
  match 'match_account_number' => 'Users#match'

end

app/models/reading.rb
# == Schema Information
#
# Table name: readings
#
#  id            :integer          not null, primary key
#  meter_reading :string(255)
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Reading < ActiveRecord::Base
  attr_accessible :meter_reading, :user_id
  belongs_to :user
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController


  # HEAD /create_meter_reading
  # GET /create_meter_reading
  def create_meter_reading
    userid = Integer(request.env["HTTP_TX_USER_ID"])
    meterreading = request.env["HTTP_TX_METER_READING"]
    @reading = Reading.create(:user_id => userid, :meter_reading => meterreading)
    respond_to do |format|
      format.json do
        if @reading.save
          response.headers["TX_UPDATE_STATUS"] = "ok"
          response.headers["TX_UPDATE_STATUS_CODE"] = "200"
        else
          response.headers["TX_UPDATE_STATUS"] = "could not create reading entry"
          response.headers["TX_UPDATE_STATUS_CODE"] = "400"
        end
        render json: @reading
      end
    end
  end

  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @readings }
    end
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/new
  # GET /readings/new.json
  def new
    @reading = Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @reading = Reading.find(params[:id])
  end

  # POST /readings
  # POST /readings.json
  def create
    if (params[:readingvalue] && params[:userid])
      @reading = Reading.create(:user_id => params[:userid], :meter_reading => params[:readingvalue])
      respond_to do |format|
        if @reading.save
          format.json do
            response.headers["tx_status"] = "ok"
            response.headers["tx_reading_id"] = @reading[:id].to_s
            response.headers["tx_dummy_header"] = request.env["HTTP_DUMMY_HEADER"]<<"_hahaha"
            #response.headers["tx_dummy_header"] = request.env["HTTP_DUMMY_HEADER"]

             # for header in request.env.select {|k,v| k.match("^HTTP.*")}
             #   response.headers["#{header[0].split('_',2)[1]}"] = "#{header[1]}"
             # end

            render json: @reading
          end
        else
          format.json do
            response.headers["tx_status"] = "error"
          end
        end
      end
    else
      @reading = Reading.new(params[:reading])

      respond_to do |format|
        if @reading.save
          format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
          format.json { render json: @reading, status: :created, location: @reading }
        else
          format.html { render action: "new" }
          format.json { render json: @reading.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.json
  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to readings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meter_reading %><br />
    <%= f.text_field :meter_reading %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.haml
%h2{style: "text-align:left"}Readings
%table{border: "1", cellpadding: 4}
  %tr
    %th Reading
    %th User
    %th Account #
    %th Created at
    %th
    %th
  -@readings.reverse.each do |reading|
    %tr
      %td= reading.meter_reading
      %td= "#{reading.user.fname} #{reading.user.lname}"
      %td= reading.user.account_number
      %td= reading.created_at.in_time_zone('Eastern Time (US & Canada)').to_formatted_s(:short)
      %td= link_to 'Edit', edit_reading_path(reading)
      %td= link_to 'Destroy', reading, method: :delete, data: { confirm: 'Are you sure?' }
    %tr
%table
%br
=link_to 'New Reading', new_reading_path

app/views/readings/new.html.erb
<h1>New reading</h1>

<%= render 'form' %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.haml
-provide(:title, 'Reading')
%p{id: "notice"}=notice
%p
  Meter reading:
  =@reading.meter_reading
%p
  %b
    User:
  =@reading.user_id
=link_to 'Edit', edit_reading_path(@reading)
|
= link_to 'Back', readings_path