config/routes.rb
TxivrWaterDemo::Application.routes.draw do
  resources :readings
  match 'create_meter_reading' => 'Readings#create_meter_reading'

  resources :users
  match 'match_account_number' => 'Users#match'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  phone_number   :string(255)
#  fname          :string(255)
#  lname          :string(255)
#  email          :string(255)
#  address        :string(255)
#  account_number :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :account_number, :address, :email, :fname, :lname, :phone_number
  has_many :readings

  before_save {|user| user.email = email.downcase}

  validates :fname, presence: true
  validates :account_number, presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates_length_of :account_number, :is => 8, :message => "should be of 8 digits"
  validates_numericality_of :account_number, :only_integer => true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  # HEAD /match_account_number
  # GET  /match_account_number

    def match
      acc_number = request.env["HTTP_TX_ACCOUNT_NUMBER"]
      ani = request.env["HTTP_TX_ANI"]
      if ani.nil?
        ani = "0"
      end
      @user = User.where(:account_number => acc_number).limit(1)[0]
      last_reading = @user.readings.last
      if last_reading.nil?
        last_reading = "0"
      else
        last_reading = last_reading.meter_reading
      end
      respond_to do |format|
        format.json do
          if @user.present?
            response.headers["TX_MATCH_STATUS"] = "ok"
            response.headers["TX_MATCH_STATUS_CODE"] = "200"
            response.headers["TX_USER_FNAME"] = @user[:fname]
            response.headers["TX_USER_LNAME"] = @user[:lname]
            response.headers["TX_USER_PHONE_NUMBER"] = @user[:phone_number].to_s
            response.headers["TX_USER_PHONE_NUMBER_LENGTH"] = @user[:phone_number].to_s.length.to_s
            response.headers["TX_USER_ID"] = @user[:id].to_s
            response.headers["TX_LAST_READING"] = last_reading
            if ani.index(@user[:phone_number])
              response.headers["TX_ANI_MATCHED"] = "yes"
            else
              response.headers["TX_ANI_MATCHED"] = "no"
            end
          else
            response.headers["TX_MATCH_STATUS"] = "not matched"
            response.headers["TX_MATCH_STATUS_CODE"] = "400"
          end
          render json: @user
        end
      end
    end

  # GET /users
  # GET /users.json
  def index
    
    if params[:number]
      @users = User.where(:phone_number => params[:number]).limit(1)
    else
      @users = User.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json do 
        #head(:tx_user => "ron")
        response.headers["tx_fname"] = @users[0][:fname]
        response.headers["tx_lname"] = @users[0][:lname]
        response.headers["tx_acc_number"] = @users[0][:account_number]
        response.headers["tx_address"] = @users[0][:address]
        response.headers["tx_email"] = @users[0][:email]
        response.headers["tx_user_id"] = @users[0][:id].to_s
        render json: @users
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @readings = @user.readings
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :account_number %><br />
    <%= f.text_field :account_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2 style="text-align:left">Users</h1>

<table border = "1" cellpadding = 4>
  <tr>
    <th>Phone number</th>
    <th>First name</th>
    <th>Last name</th>
    <th>email</th>
    <th>Address</th>
    <th>Account number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.phone_number %></td>
    <td><%= user.fname %></td>
    <td><%= user.lname %></td>
    <td><%= user.email %></td>
    <td><%= user.address %></td>
    <td><%= user.account_number %></td>
    <td><%= link_to 'Readings', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, '@user.fname') %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= "#{@user.fname} #{@user.lname}" %>
</p>

<p>
  <b>Account number:</b>
  <%= @user.account_number %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<p>
  <b>Phone number:</b>
  <%= @user.phone_number %>
</p>

<br/>
<br/>
<% if @readings.count > 1 %>
<p>
  <h2 style="text-align:left">Readings</h1>

<table border = "1" cellpadding = 4>
  <tr>
    <th>Created at</th>
    <th>Reading</th>
    <!--th></th>
    <th></th>
    <th></th-->
  </tr>

<% @readings.reverse.each do |reading| %>
  <tr>
    <td><%=  reading.created_at.in_time_zone('Eastern Time (US & Canada)').to_formatted_s(:short)%></td>
    <td><%= reading.meter_reading%></td>
    <!--td><%#= link_to 'Show', reading %></td>
    <td><%#= link_to 'Edit', edit_reading_path(reading) %></td>
    <td><%#= link_to 'Destroy', reading, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
  </tr>
<% end %>
</table>

<br />
</p>
<%else%>
No readings found.
<%end%>
<br/>
<br/>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>